api:
    entities:
        Marello\Bundle\InventoryBundle\Entity\VirtualInventoryLevel:
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    product:
                        data_type: string
                        allow_array: true
                        property_path: product
                        description: 'Filter by product'
                    channelGroup:
                        data_type: integer
                        allow_array: true
                        property_path: channelGroup
                        description: 'Filter by channel Group'
                    createdAt:
                        exclude: true
                    updatedAt:
                        exclude: true