api:
    entities:
        Marello\Bundle\InventoryBundle\Entity\VirtualInventoryLevel:
            fields:
                channels:
                    property_path: salesChannelGroup.salesChannels
                salesChannelGroup:
                    exclude: true
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    product:
                        data_type: string
                        allow_array: true
                        property_path: product.sku
                        description: 'Filter by product sku'
                    salesChannel:
                        data_type: string
                        property_path: salesChannelGroup.salesChannels.code
                        description: 'Filter levels by SalesChannels'
                    createdAt:
                        exclude: true
                    updatedAt:
                        exclude: true
            actions:
                get_subresource: false
                create: false
                update: false
                delete: false
                delete_list: false
                add_relationship: false
                get_relationship: false
                update_relationship: false
                delete_relationship: false
