marello_inventory_item:
    resource: "@MarelloInventoryBundle/Controller/InventoryController.php"
    type:     annotation
    prefix:   /marello/inventory/item

marello_inventory_level:
    resource: "@MarelloInventoryBundle/Controller/InventoryLevelController.php"
    type:     annotation
    prefix:   /marello/inventory/inventory-level

marello_inventory_warehouse:
    resource: "@MarelloInventoryBundle/Controller/WarehouseController.php"
    type:     annotation
    prefix:   /marello/inventory/warehouse
