system_configuration:
    groups:
        inventory:
            title: marello.inventory.system_configuration.groups.inventory.title
        inventory_balancing:
            title: marello.inventory.system_configuration.groups.inventory.balacing.title
            icon: fa-cubes
        inventory_balancing_strategy:
            title: marello.inventory.system_configuration.groups.inventory.balacing.strategy.label

    fields:
        marello_inventory.balancing_strategy:
            data_type: string
            type: marello_inventory_balancer_strategy_choice
            options:
                label: marello.inventory.system_configuration.fields.balancing_strategy.label
                required: true

    tree:
        system_configuration:
            marello:
                children:
                    inventory:
                        children:
                            inventory_balancing:
                                children:
                                    inventory_balancing_strategy:
                                        children:
                                            - marello_inventory.balancing_strategy
