api:
    entities:
        Marello\Bundle\OrderBundle\Entity\Order:
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
                workflowItem:
                    fields:
                        __class__:
                            property_path: sourceEntityClass
                        id:
                            property_path: sourceEntityId
                    data_type: nestedAssociation
                    fields:
                        __class__:
                            Oro\Bundle\WorkflowBundle\Entity\WorkflowItem
                        id:
                            id
            filters:
                exclusion_policy: all
                fields:
                    orderNumber:
                        data_type: string
                        allow_array: true
                        property_path: orderNumber
                        description: 'Filter by order number'
                    orderReference:
                        data_type: string
                        allow_array: true
                        property_path: orderReference
                        description: 'Filter by order reference'
                    createdAt:
                        exclude: true
                    updatedAt:
                        exclude: true
            actions:
                update: false
                delete: false
                delete_list: false
                update_relationship: false
                delete_relationship: false

        Marello\Bundle\OrderBundle\Entity\OrderItem:
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    orders:
                        data_type: integer
                        allow_array: true
                        property_path: order
                        description: 'Filter by order ID'
            actions:
                delete: false
                delete_list: false
                update_relationship: false
                delete_relationship: false

        Marello\Bundle\OrderBundle\Entity\Customer:
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    email:
                        data_type: string
                        allow_array: true
                        property_path: email
                        description: 'Filter by email'
            actions:
                delete: false
                delete_list: false
                delete_relationship: false
