oro_entity:
    entity_aliases:
        Marello\Bundle\OrderBundle\Entity\Customer:
            alias: customer
            plural_alias: customers

        Marello\Bundle\OrderBundle\Entity\Order:
            alias: order
            plural_alias: orders

        Marello\Bundle\OrderBundle\Entity\OrderItem:
            alias: orderitem
            plural_alias: orderitems
