placeholders:
    placeholders:
        marello_customer_address:
            items:
                marelloe_customer_address_map:
                    order: 100

    items:
        marello_customer_address_map:
            template: MarelloOrderBundle:Customer:customerAddressMap.html.twig
