assetic:
    assets:
        tinymce_image:
            inputs:
                - %kernel.root_dir%/../vendor/tinymce/tinymce/plugins/image/plugin.min.js
            output: bundles/tinymce/plugins/image/plugin.min.js