#
# 3rd party routes
#
nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

#
# ORO routes
#
oro_default:
    pattern:  /
    defaults:
        _controller: OroDashboardBundle:Dashboard:view

