workflows:
    marello_order_b2c_workflow_1:
        label:        'Order B2C Workflow #1'
        entity:       Marello\Bundle\OrderBundle\Entity\Order
        entity_attribute: order
        start_step:   pending
        attributes:
            payment_reference:
                label: 'Payment Reference'
                type: string
        steps:
            pending:
                label:  Pending Order
                allowed_transitions:
                    - hold_pending
                    - cancel
                    - invoice
            cancelled:
                label:  Cancelled
                allowed_transitions: []
            pending_on_hold:
                label:  On Hold
                allowed_transitions:
                    - un_hold_pending
            invoice_on_hold:
                label:  On Hold
                allowed_transitions:
                    - un_hold_invoice
            invoice:
                label:  Order Payed
                allowed_transitions:
                    - hold_invoice
                    - credit
                    - prepare_shipping
            credit:
                label:  Closed
                allowed_transitions: []
            pick_and_pack:
                label: Pick and Pack
                allowed_transitions:
                    - ship
            shipped:
                label:  Complete
                allowed_transitions: []

        transitions:
            cancel:
                label:    Cancel
                step_to:  cancelled
                transition_definition: cancel_definition
            hold_pending:
                label:    Hold
                step_to:  pending_on_hold
                transition_definition: hold_definition
            un_hold_pending:
                label:    Un-Hold
                step_to:  pending
                transition_definition: un_hold_definition
            hold_invoice:
                label:    Hold
                step_to:  invoice_on_hold
                transition_definition: hold_definition
            un_hold_invoice:
                label:    Un-Hold
                step_to:  invoice
                transition_definition: un_hold_definition
            invoice:
                label:    Invoice
                step_to:  invoice
                transition_definition: invoice_definition
                form_options:
                    attribute_fields:
                        payment_reference:
                            form_type: text
                            options:
                                required: true
                                constraints:
                                  - NotBlank: ~
                    attribute_default_values:
                        payment_reference: ''
            ship:
                label:    Ship
                step_to:  shipped
                transition_definition: ship_definition
            credit:
                label:    Credit
                step_to:  credit
                transition_definition: credit_definition
            prepare_shipping:
                label:    Prepare Shipping
                step_to:  pick_and_pack
                transition_definition: prepare_shipping_definition

        transition_definitions:
            cancel_definition:
                post_actions:
                    - @marello_cancel_order: ~
            hold_definition: []
            un_hold_definition: []
            invoice_definition:
                post_actions:
                    - @create_object:
                        class: \DateTime
                        attribute: $order.invoicedAt
            credit_definition: []
            ship_definition:
                post_actions:
                    - @marello_ship_order: ~
            prepare_shipping_definition: []
