datagrid:
    marello-inventory-item:
        source:
            type: orm
            query:
                select:
                    - p
                    - COALESCE(SUM(i.quantity), 0) AS stockLevel
                from:
                    - { table: MarelloProductBundle:Product, alias: p }
                join:
                    left:
                        - { join: p.inventoryItems, alias: i }
                groupBy: p.id
        columns:
            sku:
                label: marello.product.sku.label
                data_name: sku
            product:
                label: marello.inventory.inventoryitem.product.label
                frontend_type: string
                data_name: name
            quantity:
                label: marello.product.stock_level.label
                frontend_type: number
                data_name: stockLevel
            status:
                label: marello.product.status.label
                frontend_type: string
                data_name: status
            createdAt:
                label:              oro.ui.created_at
                frontend_type:      datetime
                data_name:          createdAt
        filters:
            columns:
                sku:
                    type:             string
                    data_name:        sku
                product:
                    type:             string
                    data_name:        name
                quantity:
                    type:             string
                    data_name:        stockLevel
                status:
                    type: entity
                    data_name: s
                    options:
                        field_options:
                            class: Marello\Bundle\ProductBundle\Entity\ProductStatus
                createdAt:
                    type:             datetime
                    data_name:        createdAt
        properties:
            inventory_link:
                type:       url
                route:      marello_inventory_inventory_update
                params:     { id: id }
        actions:
            inventory:
                type:           navigate
                icon:           list-alt
                link:           inventory_link
                rowAction:      true
        options:
            export: true

    marello-inventory-product-item:
        source:
            type: orm
            query:
                select:
                    - w
                    - SUM(i.quantity) AS  stock
                from:
                    - { table: MarelloInventoryBundle:InventoryItem, alias: i }
                join:
                    left:
                        - { join: i.warehouse, alias: w }
                groupBy: w.id
        columns:
            warehouse:
                label: Warehouse
                data_name: w
            stock:
                label: Stock
                data_name: stock
