datagrid:
    marello-inventory-item:
        source:
            type: orm
            query:
                select:
                    - p
                    - COALESCE(SUM(i.quantity), 0) AS stockLevel
                from:
                    - { table: MarelloProductBundle:Product, alias: p }
                join:
                    left:
                        - { join: p.inventoryItems, alias: i }
                groupBy: p.id
        columns:
            sku:
                label: marello.product.sku.label
                data_name: sku
            product:
                label: marello.inventory.inventoryitem.product.label
                frontend_type: string
                data_name: name
            quantity:
                label: marello.inventory.inventoryitem.quantity.label
                frontend_type: number
                data_name: stockLevel

        properties:
            inventory_link:
                type:       url
                route:      marello_inventory_inventory_update
                params:     { id: id }
        actions:
            inventory:
                type:           navigate
                icon:           list-alt
                link:           inventory_link
                rowAction:      true

    marello-inventory-product-item:
        source:
            type: orm
            query:
                select:
                    - w
                    - SUM(i.quantity) AS  stock
                from:
                    - { table: MarelloInventoryBundle:InventoryItem, alias: i }
                join:
                    left:
                        - { join: i.warehouse, alias: w }
                groupBy: w.id
        columns:
            warehouse:
                label: Warehouse
                data_name: w
            stock:
                label: Stock
                data_name: stock

    marello-inventory-log:
        source:
            type: orm
            query:
                select:
                    - l
                from:
                    - { table: MarelloInventoryBundle:InventoryLog, alias: l }
                join:
                    left:
                        - { join: l.inventoryItem, alias: i }
                where:
                    and:
                        - IDENTITY(i.product) = :product_id
            bind_parameters:
                product_id: productId
        columns:
            changeAmount:
                label: marello.inventory.inventorylog.changeAmount.label
                frontend_type: number
            actionType:
                label: marello.inventory.inventorylog.actionType.label
                frontend_type: string
            user:
                label: marello.inventory.inventorylog.user.label
                frontend_type: string
            createdAt:
                label: marello.inventory.inventorylog.createdAt.label
                frontend_type: datetime
