datagrid:
    marello-inventory-item:
        source:
            type: orm
            query:
                select:
                    - p.id
                    - p.name
                    - p.sku
                    - p.price
                    - s.label as status
                    - p.createdAt
                    - p.updatedAt
                    - COALESCE(SUM(l.stock), 0) AS quantity
                    - COALESCE(SUM(l.allocatedStock), 0) AS allocatedQuantity
                    - COALESCE(SUM(l.stock - l.allocatedStock), 0) AS virtualQuantity
                from:
                    - { table: MarelloProductBundle:Product, alias: p }
                join:
                    left:
                        - { join: p.status, alias: s }
                        - { join: p.inventoryItems, alias: i }
                        - { join: i.currentLevel, alias: l }
                groupBy: p.id
        columns:
            sku:
                label:              marello.product.sku.label
                frontend_type:      string
            product:
                label:              marello.inventory.inventoryitem.product.label
                frontend_type:      string
                data_name:          name
            quantity:
                label:              marello.inventory.inventoryitem.quantity.label
                frontend_type:      number
                data_name:          quantity
            allocatedQuantity:
                label:              marello.inventory.inventoryitem.allocated_quantity.label
                frontend_type:      number
                data_name:          allocatedQuantity
            virtualQuantity:
                label:              marello.inventory.inventoryitem.virtual_quantity.label
                frontend_type:      number
                data_name:          virtualQuantity
            status:
                label:              marello.product.status.label
                frontend_type:      string
            createdAt:
                label:              oro.ui.created_at
                frontend_type:      datetime
        filters:
            columns:
                sku:
                    type:             string
                    data_name:        p.sku
                product:
                    type:             string
                    data_name:        p.name
                quantity:
                    type:             number
                    data_name:        quantity
                allocatedQuantity:
                    type:             number
                    data_name:        allocatedQuantity
                virtualQuantity:
                    type:             number
                    data_name:        virtualQuantity
                status:
                    type:             entity
                    data_name:        s
                    options:
                        field_options:
                            class: Marello\Bundle\ProductBundle\Entity\ProductStatus
                createdAt:
                    type:             datetime
                    data_name:        createdAt
        properties:
            inventory_link:
                type:       url
                route:      marello_inventory_inventory_update
                params:     { id: id }
        actions:
            inventory:
                type:           navigate
                icon:           list-alt
                link:           inventory_link
        options:
            export: true

    marello-inventory-log:
        source:
            type: orm
            query:
                select:
                    - l
                    - (l.stock - COALESCE(p.stock, 0)) AS changeAmount
                    - (l.allocatedStock - COALESCE(p.allocatedStock, 0)) AS changeAllocatedAmount
                from:
                    - { table: MarelloInventoryBundle:StockLevel, alias: l }
                join:
                    left:
                        - { join: l.previousLevel, alias: p }
                        - { join: l.inventoryItem, alias: i }
                where:
                    and:
                        - IDENTITY(i.product) = :product_id
            bind_parameters:
                product_id: productId
        columns:
            changeAmount:
                data_name:      changeAmount
                label:          marello.inventory.stocklevel.stock_diff.label
                type:           twig
                frontend_type:  html
                template:       MarelloInventoryBundle::Datagrid/StockLevel/diff.html.twig
            changeAllocatedAmount:
                data_name:      changeAllocatedAmount
                label:          marello.inventory.stocklevel.allocated_stock_diff.label
                type:           twig
                frontend_type:  html
                template:       MarelloInventoryBundle::Datagrid/StockLevel/diff.html.twig
            changeTrigger:
                data_name:      changeTrigger
                label:          marello.inventory.stocklevel.change_trigger.label
                type:           translatable
                domain:         MarelloInventoryLogAction
                frontend_type:  string
            author:
                label:          marello.inventory.stocklevel.author.label
                frontend_type:  string
            subject:
                label:          marello.inventory.stocklevel.subject.label
                type:           twig
                frontend_type:  html
                template:       MarelloInventoryBundle::Datagrid/StockLevel/subject.html.twig
            createdAt:
                label:          oro.ui.created_at
                frontend_type:  datetime
        sorters:
            columns:
                createdAt:
                    data_name:  l.createdAt
                changeAmount:
                    data_name:  changeAmount
                changeAllocatedAmount:
                    data_name:  changeAllocatedAmount
            default:
                createdAt:      DESC
        options:
            toolbarOptions:
                pageSize:
                    default_per_page: 10

    marello-inventory-log-extended:
        extends: marello-inventory-log
        filters:
            columns:
                changeAmount:
                    type:             number
                    data_name:        changeAmount
                changeAllocatedAmount:
                    type:             number
                    data_name:        changeAllocatedAmount
                changeTrigger:
                    type:             string
                    data_name:        l.changeTrigger
                createdAt:
                    type:             datetime
                    data_name:        createdAt
        options:
            toolbarOptions:
                pageSize:
                    default_per_page: 50
