services:
    marello_inventory.form.type.warehouse:
        class: Marello\Bundle\InventoryBundle\Form\Type\WarehouseType
        tags:
            - { name: form.type, alias: marello_warehouse }

    marello_intentory.form.type.warehouse_inventory:
        class: Marello\Bundle\InventoryBundle\Form\Type\WarehouseInventoryType
        tags:
             - { name: form.type, alias: marello_warehouse_inventory }

    marello_intentory.form.type.warehouse_inventory_collection:
        class: Marello\Bundle\InventoryBundle\Form\Type\WarehouseInventoryCollectionType
        tags:
             - { name: form.type, alias: marello_warehouse_inventory_collection }

    marello_inventory.form.type.product_inventory:
        class: Marello\Bundle\InventoryBundle\Form\Type\ProductInventoryType
        tags:
             - { name: form.type, alias: marello_product_inventory }

    marello_inventory.form.type.inventory_item_collection:
        class: Marello\Bundle\InventoryBundle\Form\Type\InventoryItemCollectionType
        arguments:
            - @marello_inventory.form.subscriber.inventory_item_collection
        tags:
            - { name: form.type, alias: marello_inventory_item_collection }

    marello_inventory.form.type.inventory_item:
        class: Marello\Bundle\InventoryBundle\Form\Type\InventoryItemType
        tags:
            - { name: form.type, alias: marello_inventory_item }

    marello_inventory.form.subscriber.inventory_item_collection:
        class: Marello\Bundle\InventoryBundle\Form\Subscriber\InventoryItemCollectionSubscriber
        arguments:
            - @doctrine
