oro_menu_config:
    items:
        warehouses:
            label: marello.inventory.warehouse.entity_plural_label
            route: marello_inventory_warehouse_updatedefault
            extras:
                routes: ['marello_inventory_warehouse_*']
    tree:
        application_menu:
            children:
                system_tab:
                    children:
                        warehouses: ~

oro_titles:
    marello_inventory_warehouse_updatedefault: 'Default Warehouse - Update'
