parameters:
    marello_inventory.entity.warehouse.class: Marello\Bundle\InventoryBundle\Entity\Warehouse

services:
    marello_product.widget_provider.actions.variant_mass_inventory:
        parent: oro_ui.widget_provider.action_button.abstract
        arguments:
            - marello_variant_mass_inventory_button
            - marello_variant_mass_inventory_link
        tags:
            - { name: oro_ui.view_action_provider, group: product }

    marello_inventory.logging.chart_builder:
        class: Marello\Bundle\InventoryBundle\Logging\ChartBuilder
        arguments:
            - '@doctrine'
            - '@oro_dashboard.datetime.helper'
            - '@translator'

    marello_inventory.listener.doctrine.stock_level_hydration:
        class: Marello\Bundle\InventoryBundle\EventListener\Doctrine\StockLevelSubjectHydrationSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    marello_inventory.listener.doctrine.stock_level_author_fill:
        class: Marello\Bundle\InventoryBundle\EventListener\Doctrine\StockLevelAuthorFillSubscriber
        arguments:
            - '@security.token_storage'
        tags:
            - { name: doctrine.event_subscriber }

    marello_inventory.listener.doctrine.stock_level_subject_delayed_assign:
        class: Marello\Bundle\InventoryBundle\EventListener\Doctrine\StockLevelSubjectAssignSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    marello_inventory.event_listener.inventory_update_event_listener:
        class: 'Marello\Bundle\InventoryBundle\EventListener\InventoryUpdateEventListener'
        arguments:
            - '@marello_inventory.manager.inventory_manager'
        tags:
            - { name: kernel.event_listener, event: marello_inventory.inventory.update, method: handleUpdateInventoryEvent }

    marello_inventory.manager.inventory_manager:
        class: Marello\Bundle\InventoryBundle\Manager\InventoryManager
