services:
    marello_product.widget_provider.actions.variant_mass_inventory:
        parent: oro_ui.widget_provider.action_button.abstract
        arguments:
            - marello_variant_mass_inventory_button
            - marello_variant_mass_inventory_link
        tags:
            - { name: oro_ui.view_action_provider, group: product }

    marello_inventory.logging.inventory_logger:
        class: Marello\Bundle\InventoryBundle\Logging\InventoryLogger
        arguments:
            - @doctrine

    marello_inventory.logging.handler.manual:
        class: Marello\Bundle\InventoryBundle\Logging\InventoryLogActionHandler
        tags:
            - { name: marello_inventory.logging.inventory_logger, type: manual }

    marello_inventory.event_listener.doctrine.product_inventory_log:
        class: Marello\Bundle\InventoryBundle\EventListener\Doctrine\ProductInventoryLogListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    marello_inventory.event_listener.inventory_log:
        class: Marello\Bundle\InventoryBundle\EventListener\InventoryLogListener
        arguments:
            - @doctrine
        tags:
            - { name: kernel.event_listener, event: marello.inventory.log, method: log }
