parameters:
    marello_inventory.entity.warehouse.class: Marello\Bundle\InventoryBundle\Entity\Warehouse

services:
    marello_product.widget_provider.actions.variant_mass_inventory:
        parent: oro_ui.widget_provider.action_button.abstract
        arguments:
            - marello_variant_mass_inventory_button
            - marello_variant_mass_inventory_link
        tags:
            - { name: oro_ui.view_action_provider, group: product }

    marello_inventory.logging.chart_builder:
        class: Marello\Bundle\InventoryBundle\Logging\ChartBuilder
        arguments:
            - '@doctrine'
            - '@oro_dashboard.datetime.helper'
            - '@translator'

    marello_inventory.listener.doctrine.stock_level_hydration:
        class: Marello\Bundle\InventoryBundle\EventListener\Doctrine\StockLevelSubjectHydrationSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    marello_inventory.listener.doctrine.stock_level_author_fill:
        class: Marello\Bundle\InventoryBundle\EventListener\Doctrine\StockLevelAuthorFillSubscriber
        arguments:
            - '@security.token_storage'
        tags:
            - { name: doctrine.event_subscriber }

    marello_inventory.listener.doctrine.stock_level_subject_delayed_assign:
        class: Marello\Bundle\InventoryBundle\EventListener\Doctrine\StockLevelSubjectAssignSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    marello_inventory.event_listener.inventory_update_event_listener:
        class: 'Marello\Bundle\InventoryBundle\EventListener\InventoryUpdateEventListener'
        arguments:
            - '@marello_inventory.manager.inventory_balance_manager'
        tags:
            - { name: kernel.event_listener, event: marello_inventory.inventory.update, method: handleUpdateInventoryEvent }

    # Inventory Balancers and related services
    marello_inventory.manager.marello_inventory_balancer_registry:
        class: Marello\Bundle\InventoryBundle\Manager\InventoryBalancerRegistry
        arguments:
            - '@service_container'

    marello_inventory.manager.inventory_balance_manager:
        class: Marello\Bundle\InventoryBundle\Manager\InventoryBalancerManager
        arguments:
            - '@marello_inventory.manager.marello_inventory_balancer_registry'
            - '@oro_config.manager'

    marello_inventory.manager.balancer.abstract_balancer:
        class: Marello\Bundle\InventoryBundle\Manager\Balancer\AbstractInventoryBalancer
        abstract: true
        arguments:
            - '@marello_inventory.manager.inventory_manager'

    marello_inventory.manager.balancer.single_warehouse_balancer:
        class: Marello\Bundle\InventoryBundle\Manager\Balancer\SingleWarehouseBalancer
        parent: marello_inventory.manager.balancer.abstract_balancer
        tags:
            - { name: marello_inventory.manager.balancer.inventory_balancer, alias: single_warehouse_balancer }

    marello_inventory.manager.inventory_manager:
        class: Marello\Bundle\InventoryBundle\Manager\InventoryManager
        arguments:
            - '@doctrine.orm.entity_manager'
