services:
    marello_product.widget_provider.actions.variant_mass_inventory:
        parent: oro_ui.widget_provider.action_button.abstract
        arguments:
            - marello_variant_mass_inventory_button
            - marello_variant_mass_inventory_link
        tags:
            - { name: oro_ui.view_action_provider, group: product }

    marello_inventory.logging.chart_builder:
        class: Marello\Bundle\InventoryBundle\Logging\ChartBuilder
        arguments:
            - @doctrine
            - @oro_dashboard.datetime.helper
            - @translator

    marello_inventory.listener.doctrine.stock_level_hydration:
        class: Marello\Bundle\InventoryBundle\EventListener\Doctrine\StockLevelSubjectHydrationSubscriber
        tags:
            - { name: doctrine.event_subscriber }
