services:
    marello_commerce_bridge.event_listener.navigation_listener:
        class: Marello\Bridge\MarelloCommerce\EventListener\NavigationListener
        arguments:
            - '@translator.default'
        tags:
            - { name: kernel.event_listener, event: oro_menu.configure.application_menu, method: onNavigationConfigure }

    marello_commerce_bridge.event_listener.widget_items_load_data:
        class: Marello\Bridge\MarelloCommerce\EventListener\WidgetConfigurationLoadListener
        arguments:
            - '@translator.default'
        tags:
            - { name: kernel.event_listener, event: oro_dashboard.widget_configuration_load, method: onConfigurationLoad, priority: -100 }

    marello_commerce_bridge.entity_alias_provider:
        class: Marello\Bridge\MarelloCommerce\Provider\MarelloEntityAliasProvider
        public: false
        tags:
            - { name: oro_entity.alias_provider }

    marello_commerce_bridge.workflow.action.send_email_template.marello_decorator:
        class: 'Marello\Bridge\MarelloCommerce\Workflow\Action\SendEmailTemplateMarelloDecorator'
        public: false
        decorates: oro_email.workflow.action.send_email_template
        arguments:
            - '@marello_commerce_bridge.workflow.action.send_email_template.marello_decorator.inner'