datagrids:
    marello-shipping-methods-configs-rule-grid:
        acl_resource: marello_shipping_methods_configs_rule_view
        extended_entity_name: '%marello_shipping.entity.shipping_methods_configs_rule.class%'
        options:
            entityHint:        shipping rules
            entity_pagination: true
        source:
            type:         orm
            query:
                select:
                    - shipping_methods_configs_rule
                    - shipping_methods_configs_rule.id
                    - rule.name
                    - rule.enabled
                    - rule.sortOrder
                    - shipping_methods_configs_rule.currency
                    - rule.expression
                from:
                    - { table: '%marello_shipping.entity.shipping_methods_configs_rule.class%', alias: shipping_methods_configs_rule }
                join:
                    inner:
                        - { join: shipping_methods_configs_rule.rule, alias: rule }
                    left:
                        - { join: shipping_methods_configs_rule.methodConfigs, alias: methodConfig }

        columns:
            id:
                label:         marello.shipping.shippingmethodsconfigsrule.id.label
            name:
                label:         marello.rule.name.label
            enabled:
                label:         marello.rule.enabled.label
                frontend_type: boolean
            sortOrder:
                label:         marello.rule.sort_order.label
            currency:
                label:         marello.shipping.shippingmethodsconfigsrule.currency.label
            expression:
                label:         marello.rule.expression.label
            methodConfigs:
                label:         marello.shipping.shippingmethodsconfigsrule.method_configs.label
                type:          twig
                frontend_type: html
                template:      MarelloShippingBundle:ShippingMethodsConfigsRule:Datagrid/configurations.html.twig
            destinations:
                label:         marello.shipping.shippingmethodsconfigsrule.destinations.label
                type:          twig
                frontend_type: html
                template:      MarelloShippingBundle:ShippingMethodsConfigsRule:Datagrid/destinations.html.twig
        properties:
            id: ~
            view_link:
                type:    url
                route:   marello_shipping_methods_configs_rule_view
                params:  [ id ]
            enable_link:
                type:       url
                route:      marello_api_enable_shippingrules
                params:     [ id ]
            disable_link:
                type:       url
                route:      marello_api_disable_shippingrules
                params:     [ id ]