parameters:
    marello_datagrid.event_listener.datagrid.workflow_grid_listener.class: Marello\Bundle\DataGridBundle\EventListener\Datagrid\WorkflowGridListener

services:
    marello_datagrid.datagridhelper:
        class: Marello\Bundle\DataGridBundle\Helper\DatagridHelper