oro_menu_config:
    items:
        refunds:
            label: marello.refund.entity_plural_label
            route: marello_refund_index
            extras:
                routes: ['marello_return_*']
                position: 30

    tree:
        application_menu:
            children:
                refunds:
                    children:
                        refunds: ~

oro_titles:
    marello_return_index: marello.refund.entity_plural_label
