workflows:
    marello_refund_workflow:
        label:  "Marello refund workflow"
        entity: Marello\Bundle\RefundBundle\Entity\Refund
        entity_attribute: refund
        start_step: pending
        steps:
            pending:
                label: Pending Refund
                allowed_transitions:
                    - approve
            approved:
                label: Approved Refund
                allowed_transitions:
                    - complete
            completed:
                label: Complete Refund
                allowed_transitions: []

        transitions:
            approve:
                label: Approve
                step_to: approved
                transition_definition: approve_definition
            complete:
                label: Complete
                step_to: completed
                transition_definition: complete_definition

        transition_definitions:
            approve_definition: []
            complete_definition:
                post_actions:
                    - @marello_notification_send:
                        entity: $refund
                        recipient: $refund.order.customer.email
                        template: marello_refund_credited
