api:
    entities:
        Marello\Bundle\SalesBundle\Entity\SalesChannel:
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    createdAt:
                        exclude: true
                    updatedAt:
                        exclude: true