datagrids:
    marello-sales-channel:
        source:
            type: orm
            query:
                select:
                    - sc
                from:
                    - { table: MarelloSalesBundle:SalesChannel, alias: sc }
        columns:
            id:
                label:                marello.sales.saleschannel.id.label
                frontend_type:        string
            name:
                label:                marello.sales.saleschannel.name.label
                frontend_type:        string
            code:
                label:                marello.sales.saleschannel.code.label
                frontend_type:        string
            channelType:
                label:                marello.sales.saleschannel.channel_type.label
                frontend_type:        string
            currency:
                label:                marello.sales.saleschannel.currency.label
                frontend_type:        string
            active:
                label:                marello.sales.saleschannel.active.label
                frontend_type:        boolean
            default:
                label:                marello.sales.saleschannel.default.label
                frontend_type:        boolean
        filters:
            columns:
                name:
                    type: string
                    data_name: sc.name
                code:
                    type: string
                    data_name: sc.code
                channelType:
                    type: string
                    data_name: sc.channelType
                currency:
                    type: string
                    data_name: sc.currency
                active:
                    type: boolean
                    data_name: sc.active
                default:
                    type: boolean
                    data_name: sc.default
        sorters:
            columns:
                id:
                    data_name: sc.id
                name:
                    data_name: sc.name
                code:
                    data_name: sc.code
                channelType:
                    data_name: sc.channelType
                currency:
                    data_name: sc.currency
                active:
                    data_name: sc.active
                default:
                    data_name: sc.default
            default:
                id: "%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC"
        properties:
            id: ~
            delete_link:
                type:   url
                route:  marello_sales_saleschannel_delete
                params: [ id ]
            edit_link:
                type:   url
                route:  marello_sales_saleschannel_update
                params: [ id ]
        actions:
            edit:
                type:          navigate
                link:          edit_link
                icon:          edit
                rowAction:     true
            delete:
                type:          delete
                link:          delete_link
                label:         oro.grid.action.delete
                confirmation:  true
                icon:          trash
        options:
            entityHint: sales_channel
            entity_pagination: true
