oro_entity:
    entity_aliases:
        Marello\Bundle\SalesBundle\Entity\SalesChannel:
            alias: saleschannel
            plural_alias: saleschannels

        Marello\Bundle\SalesBundle\Entity\SalesChannelGroup:
            alias: saleschannelgroup
            plural_alias: saleschannelgroups
