parameters:
    marello_pdf.placeholder.filter.class:            Marello\Bundle\PdfBundle\Placeholder\MarelloPlaceholderFilter

services:
    marello_pdf.widget_provider.actions:
        parent: 																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																													oro_ui.widget_provider.action_button.abstract
        arguments:
            - marello_pmanager_add_button
            - marello_pmanager_add_link
        tags:
            - { name: oro_ui.view_action_provider, group: activity, priority: 100 }
            - { name: oro_ui.update_action_provider, group: activity, priority: 100 }

    marello_pdf.placeholder.filter:
        class: %marello_pdf.placeholder.filter.class%
        arguments:
            - @ibnab_pmanager.provider.configuration
            - @oro_entity.doctrine_helper