oro_menu_config:
    items:
        sales:
            label: marello.sales.navigation.sales.label
            uri: '#'
        sales_channel:
            label: marello.sales.saleschannel.entity_plural_label
            route: marello_sales_saleschannel_index
            extras:
                routes: ['marello_sales_saleschannel_*']
    tree:
        application_menu:
            children:
                sales: ~
                system_tab:
                    children:
                        sales_channel: ~

oro_titles:
    marello_sales_saleschannel_index:   marello.sales.saleschannel.entity_plural_label
    marello_sales_saleschannel_create:  New Sales Channel
    marello_sales_saleschannel_update:  '%%name%% - Update'
