parameters:
    marello_sales.saleschannel.entity.class:                        Marello\Bundle\SalesBundle\Entity\SalesChannel
    marello_sales.saleschannel.model.channel_aware_interface.class: Marello\Bundle\SalesBundle\Model\SalesChannelAwareInterface

services:
    marello_sales.form.event_listener.default_sales_channel_subscriber:
        class: Marello\Bundle\SalesBundle\Form\EventListener\DefaultSalesChannelSubscriber
        arguments:
            - '@doctrine.orm.entity_manager'

    marello_sales.form.event_listener.sales_channel_form_subscriber:
        class: Marello\Bundle\SalesBundle\Form\EventListener\SalesChannelFormSubscriber
        arguments:
            - '@oro_locale.settings'

    marello_sales.saleschannel.provider.channel_provider:
        class: Marello\Bundle\SalesBundle\Provider\ChannelProvider
        arguments:
            - '@doctrine.orm.entity_manager'

    # Autocomplete search handler
    marello_sales.saleschannel.form.autocomplete.search_handler:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - "%marello_sales.saleschannel.entity.class%"
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: saleschannels, acl_resource: marello_product_view }

    marello_sales.active_saleschannels.form.autocomplete.search_handler:
        class: 'Marello\Bundle\SalesBundle\Autocomplete\ActiveSalesChannelHandler'
        parent: oro_form.autocomplete.search_handler
        arguments:
            - "%marello_sales.saleschannel.entity.class%"
            - ["name", "code", "channelType"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: active_saleschannels, acl_resource: marello_product_view }

    marello_sales.system_group_saleschannels.form.autocomplete.search_handler:
        class: 'Marello\Bundle\SalesBundle\Autocomplete\SystemGroupSalesChannelHandler'
        parent: oro_form.autocomplete.search_handler
        arguments:
            - "%marello_sales.saleschannel.entity.class%"
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: system_group_saleschannels, acl_resource: marello_product_view }

    marello_sales.repository.sales_channel:
        class: 'Marello\Bundle\SalesBundle\Entity\Repository\SalesChannelRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - 'Marello\Bundle\SalesBundle\Entity\SalesChannel'
        calls:
            - [setAclHelper, ['@oro_security.acl_helper']]

    marello_sales.twig.sales_extension:
        class: Marello\Bundle\SalesBundle\Twig\SalesExtension
        arguments:
            - '@marello_sales.repository.sales_channel'
        tags:
            - { name: twig.extension }

    marello_sales.listener.doctrine.sales_channel.system_group:
        class: 'Marello\Bundle\SalesBundle\EventListener\Doctrine\SalesChannelSystemGroupListener'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Marello\Bundle\SalesBundle\Entity\SalesChannel', event: prePersist }

    marello_sales.listener.doctrine.sales_channel_group.remove:
        class: 'Marello\Bundle\SalesBundle\EventListener\Doctrine\SalesChannelGroupRemoveListener'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Marello\Bundle\SalesBundle\Entity\SalesChannelGroup', event: preRemove }
