parameters:
    marello_sales.saleschannel.entity.class:      Marello\Bundle\SalesBundle\Entity\SalesChannel
    marello_sales.saleschannel.subscriber.class:  Marello\Bundle\SalesBundle\Form\EventListener\DefaultSalesChannelFieldSubscriber
    marello_sales.saleschannel.model.channel_aware_interface.class:  Marello\Bundle\SalesBundle\Model\SalesChannelAwareInterface

services:
    # Autocomplete search handler
    marello_sales.saleschannel.form.autocomplete.search_handler:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - %marello_sales.saleschannel.entity.class%
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: saleschannels, acl_resource: marello_product_view }
