oro_system_configuration:
    groups:
        sales:
            title: marello.sales.system_configuration.groups.saleschannels.title
            icon:  'icon-sitemap'
            page_reload: true
        saleschannels_saleschannel:
            title: marello.sales.system_configuration.groups.saleschannels_saleschannel.title

    fields:
        marello_sales.default_channels:
            data_type: string
            type: marello_sales_saleschannel_select
            priority: 10
            options:
                label: marello.sales.system_configuration.fields.default_channel.label

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            sales:
                                priority: 100
                                children:
                                    saleschannels_saleschannel:
                                        priority: 100
                                        children:
                                            - marello_sales.default_channels

    api_tree:
        saleschannels_saleschannel:
            marello_sales.default_channels: ~