marello_purchase_order_update:
    type:       entity
    class:      MarelloPurchaseOrderBundle:PurchaseOrder
    permission: EDIT

marello_purchase_order_view:
    type:       entity
    class:      MarelloPurchaseOrderBundle:PurchaseOrder
    permission: VIEW
