datagrid:
    marello-purchase-order:
        source:
            type: orm
            query:
                select:
                    - po
                from:
                    - { table: MarelloPurchaseOrderBundle:PurchaseOrder, alias: po }
        columns:
            purchaseOrderNumber:
                label:              marello.purchaseorder.purchase_order_number.label
                frontend_type:      string
            createdAt:
                label:              oro.ui.created_at
                frontend_type:      datetime
            updatedAt:
                label:              oro.ui.updated_at
                frontend_type:      datetime
        sorters:
            columns:
                purchaseOrderNumber:
                    data_name:      po.purchaseOrderNumber
                createdAt:
                    data_name:      po.createdAt
                updatedAt:
                    data_name:      po.updatedAt
            default:
                purchaseOrderNumber: "%oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC"
        filters:
            columns:
                purchaseOrderNumber:
                    type: string
                    data_name: po.purchaseOrderNumber
                createdAt:
                    type: datetime
                    data_name: po.createdAt
                updatedAt:
                    type: datetime
                    data_name: po.updatedAt
        properties:
            id: ~
            view_link:
                type: url
                route: marello_purchaseorder_purchaseorder_view
                params:
                    - id
        actions:
            view:
                type:          navigate
                label:         oro.grid.action.view
                link:          view_link
                icon:          eye-open
                acl_resource:  marello_purchase_order_view
                rowAction:     true

    marello-purchase-order-items:
        source:
            type: orm
            query:
                select:
                    - poi
                from:
                    - { table: MarelloPurchaseOrderBundle:PurchaseOrderItem, alias: poi }
                where:
                    and:
                        - IDENTITY(poi.order) = :order_id
            bind_parameters:
                order_id: order_id
        columns:
            productSku:
                label: marello.product.sku.label
                frontend_type: string
            productName:
                label: marello.product.name.label
                frontend_type: string
            orderedAmount:
                label: marello.purchaseorder.purchaseorderitem.ordered_amount.label
                frontend_type: number
            receivedAmount:
                label: marello.purchaseorder.purchaseorderitem.received_amount.label
                frontend_type: number

    marello-purchase-order-item-candidates:
        source:
            type: orm
            query:
                select:
                    - p.id
                    - p.sku
                    - p.name
                    - p.desiredStockLevel
                    - p.purchaseStockLevel
                    - COALESCE(SUM(l.stock - l.allocatedStock), 0) AS virtualQuantity
                    - (p.desiredStockLevel - COALESCE(SUM(l.stock - l.allocatedStock), 0)) AS orderAmount
                from:
                    - { table: MarelloProductBundle:Product, alias: p }
                join:
                    left:
                        - { join: p.inventoryItems, alias: i }
                        - { join: i.currentLevel, alias: l }
                        - { join: p.status, alias: s }
                where:
                    and:
                        - s.name = 'enabled'                                          # Only select product with enabled status
                        - >
                            p.id NOT IN (
                                SELECT
                                    IDENTITY(poi.product)
                                FROM
                                    MarelloPurchaseOrderBundle:PurchaseOrderItem poi
                                LEFT JOIN
                                    poi.order po
                                LEFT JOIN
                                    po.workflowStep ws
                                WHERE
                                    ws.name = 'pending'
                            )
                having: SUM(l.stock - l.allocatedStock) < p.purchaseStockLevel  # Only products with virtual stock lower than required purchase stock level
                groupBy: p.id

        columns:
            sku:
                label:              marello.product.sku.label
                frontend_type:      string
            name:
                label:              marello.product.name.label
                frontend_type:      string
            desiredStockLevel:
                label:              marello.product.desired_stock_level.label
                frontend_type:      number
            purchaseStockLevel:
                label:              marello.product.purchase_stock_level.label
                frontend_type:      number
            virtualQuantity:
                label:              marello.inventory.inventoryitem.virtualQuantity.label
                frontend_type:      number
                data_name:          virtualQuantity
            orderAmount:
                label:              marello.purchaseorder.purchaseorderitem.order_amount.label
                frontend_type:      number
                data_name:          orderAmount

        filters:
            columns:
                sku:
                    type: string
                    data_name: p.sku
                name:
                    type: string
                    data_name: p.name

        properties:
            id: ~
            view_link:
                type: url
                route: marello_product_view
                params:
                    - id

        actions:
            view:
                type:          navigate
                label:         oro.grid.action.view
                link:          view_link
                icon:          eye-open
                acl_resource:  marello_product_view
                rowAction:     true

        mass_actions:
            create_po:
                type: redirect
                route: marello_purchaseorder_purchaseorder_create
                label: Create PO
                icon: edit
                data_identifier: p.id

