services:
    marello_purchase_order.form.type.purchase_order_create:
        class: Marello\Bundle\PurchaseOrderBundle\Form\Type\PurchaseOrderCreateType
        tags:
            - {name: form.type, alias: marello_purchase_order_create}

    marello_purchase_order.form.type.purchase_order_item:
        class: Marello\Bundle\PurchaseOrderBundle\Form\Type\PurchaseOrderItemType
        tags:
            - {name: form.type, alias: marello_purchase_order_item }

    marello_purchase_order.form.type.purchase_order_item_collection:
        class: Marello\Bundle\PurchaseOrderBundle\Form\Type\PurchaseOrderItemCollectionType
        tags:
            - {name: form.type, alias: marello_purchase_order_item_collection }
