parameters:
    marello_purchaseorder.entity.purchaseorder.class: Marello\Bundle\PurchaseOrderBundle\Entity\PurchaseOrder

services:
    marello_purchaseorder.processor.note_activity_processor:
        class: Marello\Bundle\PurchaseOrderBundle\Processor\NoteActivityProcessor
        arguments:
            - '@marello_purchaseorder.oro_note_entity_service'
            - '@doctrine.orm.entity_manager'

    marello_purchaseorder.oro_note_entity_service:
        class: '%oro_note.entity.class%'

    marello_purchaseorder.workflow.receive_purchase_order:
        class: Marello\Bundle\PurchaseOrderBundle\Workflow\Action\ReceivePurchaseOrderAction
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@doctrine.orm.entity_manager'
            - '@marello_purchaseorder.processor.note_activity_processor'
        tags:
            - { name: oro_action.action, alias: marello_receive_purchase_order }

    marello_purchaseorder.workflow.action.transit_complete_action:
        class: Marello\Bundle\PurchaseOrderBundle\Workflow\Action\TransitCompleteAction
        parent: marello_core.workflow.action.workflow_transit_action
        tags:
            - { name: oro_action.action, alias: marello_purchase_order_transit_complete_action }

    marello_purchaseorder.listener.datagrid.purchaseorder_grid_listener:
        class: Marello\Bundle\PurchaseOrderBundle\EventListener\Datagrid\PurchaseOrderGridListener
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oro_workflow.manager'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.marello-purchase-order-item-candidates, method: buildBefore }

    marello_purchaseorder.twig.purchaseorder_extension:
        class: Marello\Bundle\PurchaseOrderBundle\Twig\PurchaseOrderExtension
        arguments:
            - '@oro_workflow.manager'
        tags:
            - { name: twig.extension }