parameters:
    marello_purchaseorder.entity.purchaseorder.class: Marello\Bundle\PurchaseOrderBundle\Entity\PurchaseOrder

services:
    marello_purchaseorder.processor.note_activity_processor:
        class: Marello\Bundle\PurchaseOrderBundle\Processor\NoteActivityProcessor
        arguments:
            - '@doctrine.orm.entity_manager'

    marello_purchaseorder.workflow.receive_purchase_order:
        class: Marello\Bundle\PurchaseOrderBundle\Workflow\Action\ReceivePurchaseOrderAction
        arguments:
            - '@oro_action.context_accessor'
            - '@doctrine.orm.entity_manager'
            - '@marello_purchaseorder.processor.note_activity_processor'
        tags:
            - { name: oro_workflow.action, alias: marello_receive_purchase_order }
