workflows:
    marello_purchase_order_workflow:
        label: "Purchase Order Workflow"
        entity: Marello\Bundle\PurchaseOrderBundle\Entity\PurchaseOrder
        entity_attribute: po
        start_step: pending
        attributes:
            received_items:
                label: 'Received Items'
                type: object
                options:
                    class: Marello\Bundle\PurchaseOrderBundle\Entity\PurchaseOrder
        steps:
            pending:
                label: "Pending"
                allowed_transitions:
                    - partially_receive
                    - fully_receive
            partially_received:
                label: "Partially received"
                allowed_transitions:
                    - fully_receive
            fully_received:
                label: "Fully received"
                allowed_transitions: []
        transitions:
            partially_receive:
                label:  "Receive partially"
                step_to: partially_received
                transition_definition: partially_receive_definition
                form_options:
                    attribute_fields:
                        received_items:
                            form_type: marello_po_partial_receive
                            options:
                                required: true
                                data: $po
            fully_receive:
                label:  "Receive fully"
                step_to: fully_received
                transition_definition: fully_receive_definition
        transition_definitions:
            partially_receive_definition: []
            fully_receive_definition:
                post_actions:
                    - @marello_receive_purchase_order:
                        entity: $po

