services:
    marello_shipping.integration.shipping_service_registry:
        class: Marello\Bundle\ShippingBundle\Integration\ShippingServiceRegistry
        arguments:
            - '@service_container'

    marello_shipping.workflow.action.create:
        class: Marello\Bundle\ShippingBundle\Workflow\ShipmentCreateAction
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@marello_shipping.integration.shipping_service_registry'
            - '@doctrine'
        tags:
            - { name: oro_action.action, alias: marello_shipment_create }

    marello_shipping.integration.ups.api:
        class: Marello\Bundle\ShippingBundle\Integration\UPS\UPSApi
        arguments:
            - '@oro_config.manager'

    marello_shipping.integration.ups.service_integration:
        class: Marello\Bundle\ShippingBundle\Integration\UPS\UPSShippingServiceIntegration
        arguments:
            - '@marello_shipping.integration.ups.api'
            - '@doctrine'
            - '@oro_attachment.manager'
            - '@marello_shipping.integration.ups.request_builder.shipment_confirm'
            - '@marello_shipping.integration.ups.request_builder.shipment_accept'
        tags:
            - { name: marello.shipping.integration, alias: ups }

    marello_shipping.integration.ups.service_data_factory:
        class: Marello\Bundle\ShippingBundle\Integration\UPS\UPSShippingServiceDataFactory
        arguments:
            - '@oro_config.manager'
            - '@doctrine'
        tags:
            - { name: marello.shipping.data_factory, alias: ups }

    marello_shipping.integration.manual.service_integration:
        class: Marello\Bundle\ShippingBundle\Integration\Manual\ManualShippingServiceIntegration
        arguments:
            - '@doctrine'
        tags:
            - { name: marello.shipping.integration, alias: manual }

    marello_shipping.integration.manual.service_data_factory:
        class: Marello\Bundle\ShippingBundle\Integration\Manual\ManualShippingServiceDataFactory
        arguments:
            - '@oro_config.manager'
            - '@doctrine'
        tags:
            - { name: marello.shipping.data_factory, alias: manual }

    # UPS Request buiders
    marello_shipping.integration.ups.request_builder.shipment_confirm:
        class: Marello\Bundle\ShippingBundle\Integration\UPS\RequestBuilder\ShipmentConfirmRequestBuilder
        arguments:
            - '@oro_config.manager'

    marello_shipping.integration.ups.request_builder.shipment_accept:
        class: Marello\Bundle\ShippingBundle\Integration\UPS\RequestBuilder\ShipmentAcceptRequestBuilder
        arguments:
            - '@oro_config.manager'
