oro_menu_config:
    items:
        taxes:
            label: 'marello.tax.navigation.taxes.label'
            uri: '#'
            extras:
                position: 30

        tax_code_list:
            label: 'marello.tax.taxcode.entity_plural_label'
            route: 'marello_tax_taxcode_index'
            extras:
                routes: ['marello_tax_taxcode_*']
                position: 20

        tax_rate_list:
            label: 'marello.tax.taxrate.entity_plural_label'
            route: 'marello_tax_taxrate_index'
            extras:
                routes: ['marello_tax_taxrate_*']
                position: 30

        tax_rule_list:
            label: 'marello.tax.taxrule.entity_plural_label'
            route: 'marello_tax_taxrule_index'
            extras:
                routes: ['marello_tax_taxrule_*']
                position: 10

#        shortcut_new_supplier:
#            label: 'marello.supplier.menu.shortcut_new_supplier.label'
#            route: 'marello_supplier_supplier_create'
#            extras:
#                description: 'marello.supplier.menu.shortcut_new_supplier.description'
#                isCustomAction: true
#
#        shortcut_list_suppliers:
#            label: 'marello.supplier.menu.shortcut_list_suppliers.label'
#            route: 'marello_supplier_supplier_index'
#            extras:
#                description: 'marello.supplier.menu.shortcut_list_suppliers.description'
#                isCustomAction: true


    tree:
        application_menu:
            children:
                taxes:
                    children:
                        tax_rule_list: ~
                        tax_code_list: ~
                        tax_rate_list: ~
#
#        shortcuts:
#            children:
#                shortcut_new_supplier: ~
#                shortcut_list_suppliers: ~

oro_titles:
    marello_tax_taxcode_index: 'marello.tax.taxcode.entity_plural_label'
    marello_tax_taxrate_index: 'marello.tax.taxrate.entity_plural_label'
    marello_tax_taxrule_index: 'marello.tax.taxrule.entity_plural_label'
