Marello\Bundle\TaxBundle\Entity\TaxCode:
    alias:                          marello_taxcodes
    title_fields:                   [code]
    route:
        name:                       marello_tax_taxcode_view
        parameters:
            id:                     id
    search_template: MarelloTaxBundle:TaxCode:searchResult.html.twig
    fields:
        -
            name:                   code
            target_type:            text
            target_fields:          [code]