Marello\Bundle\TaxBundle\Entity\TaxCode:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: code
            message: 'marello.tax.tax_code.messages.error.unique_code'
    properties:
        code:
            - NotBlank: ~

Marello\Bundle\TaxBundle\Entity\TaxRate:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: code
            message: 'marello.tax.tax_rate.messages.error.unique_code'
    properties:
        code:
            - NotBlank: ~
        rate:
            - NotBlank: ~