Marello\Bundle\TaxBundle\Entity\TaxCode:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: code
            message: 'marello.tax.taxcode.messages.error.unique_code'
    properties:
        code:
            - NotBlank: ~

Marello\Bundle\TaxBundle\Entity\TaxRate:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: code
            message: 'marello.tax.taxrate.messages.error.unique_code'
    properties:
        code:
            - NotBlank: ~
        rate:
            - NotBlank: ~

Marello\Bundle\TaxBundle\Entity\ProductChannelTaxRelation:
    constraints:
        - Marello\Bundle\CoreBundle\Validator\Constraints\UniqueEntityCollection:
            fields: [salesChannel, taxCode]
            errorPath: channel
            message: 'marello.tax.productchanneltaxrelation.messages.error.unique_product_channel_tax_relation'
    properties:
        salesChannel:
            - NotBlank: ~
        taxCode:
            - NotBlank: ~