api:
    entities:
        Marello\Bundle\ReturnBundle\Entity\ReturnEntity:
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    createdAt:
                        exclude: true
                    updatedAt:
                        exclude: true
            actions:
                update: false
                delete: false
                delete_list: false
                update_relationship: false
                delete_relationship: false

        Marello\Bundle\ReturnBundle\Entity\ReturnItem:
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
            actions:
                delete: false
                delete_list: false
                update_relationship: false
                delete_relationship: false
