api:
    entity_aliases:
        Marello\Bundle\ReturnBundle\Entity\ReturnEntity:
            alias: marelloreturn
            plural_alias: marelloreturns
    entities:
        Marello\Bundle\ReturnBundle\Entity\ReturnEntity:
            documentation_resource: '@MarelloReturnBundle/Resources/doc/api/return.md'