oro_entity:
    entity_aliases:
        Marello\Bundle\ReturnBundle\Entity\ReturnEntity:
            alias: return
            plural_alias: returns

        Marello\Bundle\ReturnBundle\Entity\ReturnItem:
            alias: returnitem
            plural_alias: returnitems
