datagrid:
    marello-supplier-grid:
        source:
            type: orm
            query:
                select:
                    - s
                from:
                    - { table: MarelloSupplierBundle:Supplier, alias: s }
        columns:
            name:
                label:            marello.supplier.name.label
                frontend_type:    string
            priority:
                label:            marello.supplier.priority.label
                frontend_type:    string
                data_name:        priority
            canDropship:
                label:            marello.supplier.can_dropship.label
                frontend_type:    boolean
                data_name:        canDropship
            isActive:
                label:            marello.supplier.is_active.label
                frontend_type:    boolean
                data_name:        isActive
        sorters:
            columns:
                name:
                    data_name: s.name
                priority:
                    data_name: s.priority
                canDropship:
                    data_name: s.canDropship
                isActive:
                    data_name: s.isActive
            default:
                priority: "%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC"
        filters:
            columns:
                name:
                    type: string
                    data_name: s.name
                priority:
                    type: string
                    data_name: s.priority
                canDropship:
                    type: string
                    data_name: s.canDropship
                isActive:
                    type: string
                    data_name: s.isActive
        properties:
            id: ~
            view_link:
                type:       url
                route:      marello_supplier_supplier_view
                params:     [ id ]
            update_link:
                type:       url
                route:      marello_supplier_supplier_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      marello_supplier_api_delete_supplier
                params:     [ id ]
        actions:
            view:
                type:       navigate
                link:       view_link
                icon:       eye-open
                rowAction:  true
            update:
                type:       navigate
                label:      marello.supplier.update
                icon:       edit
                link:       update_link
            delete:
                type:           delete
                link:           delete_link
                acl_resource:   marello_supplier_delete
                icon:           trash
                label:          oro.grid.action.delete
        options:
            export: true
            mass_actions:
                delete:
                    enabled: false
