datagrid:
    marello-order:
        source:
            type: orm
            query:
                select:
                    - o
                from:
                    - { table: MarelloOrderBundle:Order, alias: o }
                join:
                    left:
                        billingAddress:
                            join: o.billingAddress
                            alias: ba
                        shippingAddress:
                            join: o.shippingAddress
                            alias: sa
        columns:
            orderNumber:
                label: marello.order.order_number.label
                frontend_type: string
            salesChannel:
                label: marello.order.sales_channel.label
                frontend_type: string
                data_name: salesChannelName
            orderReference:
                label: marello.order.order_reference.label
                frontend_type: string
            billingAddress:
                frontend_type: string
                data_name: billingName                  # This alias is generated using OrderGrdiAddressFilterListener
                label: marello.order.billing_address.name.label
            shippingAddress:
                frontend_type: string
                data_name: shippingName                 # This alias is generated using OrderGrdiAddressFilterListener
                label: marello.order.shipping_address.name.label
            grandTotal:
                label: marello.order.grand_total.label
                frontend_type: currency
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label: oro.ui.updated_at
                frontend_type: datetime
        filters:
            columns:
                orderNumber:
                    type: string
                    data_name: o.orderNumber
                salesChannel:
                    type: string
                    data_name: o.salesChannelName
                orderReference:
                    type: number
                    data_name: o.orderReference
                billingAddress:
                    type: string
                    data_name: billingName              # This alias is generated using OrderGrdiAddressFilterListener
                shippingAddress:
                    type: string
                    data_name: shippingName             # This alias is generated using OrderGrdiAddressFilterListener
                createdAt:
                    type: datetime
                    data_name: o.createdAt
                updatedAt:
                    type: datetime
                    data_name: o.updatedAt
        properties:
            view_link:
                type:   url
                route:  marello_order_order_view
                params:
                    id: id
            edit_link:
                type:   url
                route:  marello_order_order_update
                params:
                    id: id
        actions:
            view:
                type:       navigate
                link:       view_link
                icon:       eye-open
                rowAction:  true
            edit:
                type:       navigate
                link:       edit_link
                icon:       edit
        options:
            export: true

    marello-order-items:
        source:
            type: orm
            query:
                select:
                    - i
                from:
                    - { table: MarelloOrderBundle:OrderItem, alias: i}
                join:
                    left:
                        product:
                            join: i.product
                            alias: product
                where:
                    and:
                        - i.order = :order_id
            bind_parameters:
                order_id: orderId
        columns:
            productSKU:
                label: marello.product.sku.label
                frontend_type: string
                data_name: product.sku
            productName:
                label: marello.product.name.label
                frontend_type: string
                data_name: product.name
            quantity:
                label: marello.order.orderitem.quantity.label
                frontend_type: number
            price:
                label: marello.order.orderitem.price.label
                frontend_type: currency
            tax:
                label: marello.order.orderitem.tax.label
                frontend_type: currency
            totalPrice:
                label: marello.order.orderitem.total_price.label
                frontend_type: currency
