datagrid:
    marello-order:
        source:
            type: orm
            query:
                select:
                    - o
                from:
                    - { table: MarelloOrderBundle:Order, alias: o}
        columns:
            id:
                label: marello.order.id.label
                frontend_type: string
#            salesChannel:
            orderReference:
                label: marello.order.order_reference.label
                frontend_type: string
            grandTotal:
                label: marello.order.grand_total.label
                frontend_type: currency
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label: oro.ui.updated_at
                frontend_type: datetime
        filters:
            columns:
                id:
                    type: number
                    data_name: o.id
                orderReference:
                    type: number
                    data_name: o.orderReference
                createdAt:
                    type: datetime
                    data_name: o.createdAt
                updatedAt:
                    type: datetime
                    data_name: o.updatedAt
        properties:
            view_link:
                type:   url
                route:  marello_order_order_view
                params:
                    id: id
        actions:
            view:
                type:       navigate
                link:       view_link
                icon:       eye-open
                rowAction:  true

    marello-order-items:
        source:
            type: orm
            query:
                select:
                    - i
                from:
                    - { table: MarelloOrderBundle:OrderItem, alias: i}
                where:
                    and:
                        - i.order = :order_id
            bind_parameters:
                order_id: orderId
        columns:
            sku:
                label: marello.order.orderitem.sku.label
                frontend_type: string
            name:
                label: marello.order.orderitem.name.label
                frontend_type: string
            quantity:
                label: marello.order.orderitem.quantity.label
                frontend_type: number
            price:
                label: marello.order.orderitem.price.label
                frontend_type: currency
