oro_menu_config:
    items:
        sales:
            label: Sales
            uri: '#'
        orders:
            label: marello.order.entity_plural_label
            route: marello_order_order_index
    tree:
        application_menu:
            children:
                sales:
                    children:
                        orders: ~
                    position: 20
