oro_menu_config:
    items:
        orders:
            label: marello.order.entity_plural_label
            route: marello_order_order_index
            extras:
                routes: ['marello_order_order_*']

        shortcut_new_order:
            label: 'marello.order.menu.shortcut_new_order.label'
            route: 'marello_order_order_create'
            extras:
                description: 'marello.order.menu.shortcut_new_order.description'
                isCustomAction: true

        shortcut_list_orders:
            label: 'marello.order.menu.shortcut_list_orders.label'
            route: 'marello_order_order_index'
            extras:
                description: 'marello.order.menu.shortcut_list_orders.description'
                isCustomAction: true

    tree:
        application_menu:
            children:
                sales:
                    children:
                        orders: ~
                    position: 20
        shortcuts:
            children:
                shortcut_new_order: ~
                shortcut_list_orders: ~

oro_titles:
    marello_order_order_index: marello.order.entity_plural_label
    marello_order_order_view: 'Order #%%id%%'
    marello_order_order_update: 'Order #%%id%% - Update'
    marello_order_order_create: 'New order'
