parameters:
    marello_order.provider.order_statistic_provider.class: Marello\Bundle\OrderBundle\Provider\OrderDashboardStatisticProvider
    marello_order_customer.class: Marello\Bundle\OrderBundle\Entity\Customer

services:
    marello_order.listener.datagrid.order_grid_address_filter_listener:
        class: Marello\Bundle\OrderBundle\EventListener\Datagrid\OrderGridAddressFilterListener
        arguments:
            - @oro_locale.dql.formatter.name
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.marello-order, method: onBuildBefore }

    marello_order.email_processor_link:
        tags:
            - { name: oro_service_link, service: marello_notification.email.send_processor }

    marello_order.listener.order_created_notification_sender:
        class: Marello\Bundle\OrderBundle\EventListener\OrderCreatedNotificationSender
        arguments:
            - "@marello_order.email_processor_link"
        tags:
            - { name: kernel.event_listener, event: "marello.core.derived_property_set", method: derivedPropertySet }

    marello_order.listener.doctrine.order_number_generator_listener:
        class: Marello\Bundle\OrderBundle\EventListener\Doctrine\OrderOrganizationListener
        arguments:
            - '@security.token_storage'
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    marello_order.manager.order.api:
        class: Marello\Bundle\OrderBundle\Entity\Manager\OrderApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %marello_order.entity.order.class%
            - @doctrine.orm.entity_manager

    marello_order.manager.customer.api:
        class: Marello\Bundle\OrderBundle\Entity\Manager\CustomerApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %marello_order_customer.class%
            - @doctrine.orm.entity_manager

    marello_order.provider.order_statistic_provider:
        class: %marello_order.provider.order_statistic_provider.class%
        arguments:
            - @doctrine
            - @oro_locale.formatter.number
            - @oro_locale.formatter.date_time
            - @oro_security.acl_helper
            - @translator.default

    marello_order.provider.customer_email_owner:
        class: Marello\Bundle\OrderBundle\Provider\CustomerEmailOwnerProvider
        tags:
            - { name: oro_email.owner.provider, order: 1 }

    marello_order.search_handler.customer:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - %marello_order_customer.class%
            - ["namePrefix", "firstName", "middleName", "lastName", "nameSuffix"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: marello_customers, acl_resource: marello_customer_view }
