parameters:
    marello_order.provider.order_statistic_provider.class: Marello\Bundle\OrderBundle\Provider\OrderDashboardStatisticProvider
services:
    marello_order.listener.datagrid.order_grid_address_filter_listener:
        class: Marello\Bundle\OrderBundle\EventListener\Datagrid\OrderGridAddressFilterListener
        arguments:
            - @oro_locale.dql.formatter.name
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.marello-order, method: onBuildBefore }

    marello_order.listener.doctrine.order_number_generator_listener:
        class: Marello\Bundle\OrderBundle\EventListener\Doctrine\OrderNumberGeneratorListener
        tags:
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: postFlush }

    marello_order.manager.order.api:
        class: Marello\Bundle\OrderBundle\Entity\Manager\OrderApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %marello_order.entity.order.class%
            - @doctrine.orm.entity_manager

    marello_order.provider.order_statistic_provider:
        class: %marello_order.provider.order_statistic_provider.class%
        arguments:
            - @doctrine
            - @oro_locale.formatter.number
            - @oro_locale.formatter.date_time
            - @oro_security.acl_helper
            - @translator.default

    marello_order.event_listener.doctrine.order_inventory_allocation_listener:
        class: Marello\Bundle\OrderBundle\EventListener\Doctrine\OrderInventoryAllocationListener
        arguments:
            - @marello_inventory.allocation.allocator
            - @marello_inventory.logging.inventory_logger
        tags:
            - { name: doctrine.event_listener, event: postPersist, method: postPersist }
