Marello\Bundle\AddressBundle\Entity\MarelloAddress:
    properties:
        street:
            - NotBlank: ~
        city:
            - NotBlank: ~
        postalCode:
            - NotBlank: ~
    constraints: ~

Marello\Bundle\OrderBundle\Entity\OrderItem:
    properties:
        product:
            - NotBlank: ~
        price:
            - NotBlank: ~
        tax:
            - NotBlank: ~
        rowTotalInclTax:
            - NotBlank: ~
        rowTotalExclTax:
            - NotBlank: ~
    constraints: ~

Marello\Bundle\OrderBundle\Entity\Order:
    properties:
        salesChannel:
            - NotBlank: ~
