Marello\Bundle\AddressBundle\Entity\Address:
    properties:
        street:
            - NotBlank: ~
        city:
            - NotBlank: ~
        postalCode:
            - NotBlank: ~
    constraints: ~
