services:
    marello_core.workflow.action.workflow_transit_action:
        class: Marello\Bundle\CoreBundle\Workflow\Action\WorkflowTransitAction
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@oro_workflow.manager'
        tags:
            - { name: oro_action.action, alias: marello_core_transit_complete_action }

    marello_productprice.validator.unique.unique_entity_collection:
        class: Marello\Bundle\CoreBundle\Validator\UniqueEntityCollectionValidator
        arguments:
            - '@doctrine'
        tags:
            - { name: validator.constraint_validator, alias: unique_entity_collection }

    marello_core.twig.workflow_extension:
        class: Marello\Bundle\CoreBundle\Twig\WorkflowExtension
        arguments:
            - '@oro_workflow.manager'
        tags:
            - { name: twig.extension }


    marello_core.extension.translation_packages_provider:
        class: Marello\Bundle\CoreBundle\Provider\TranslationPackagesProviderExtension
        tags:
            - { name: oro_translation.extension.packages_provider }

    marello_core.form.url_generator:
        class: Marello\Bundle\CoreBundle\Form\UrlGenerator
        arguments:
            - '@oro_platform.provider.package'
            - '@oro_platform.url.cache'
            - '@request_stack'