services:
    marello_core.workflow.action.workflow_transit_action:
        class: Marello\Bundle\CoreBundle\Workflow\Action\WorkflowTransitAction
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: oro_action.action, alias: marello_core_transit_complete_action }

    marello_productprice.validator.unique.unique_entity_collection:
        class: Marello\Bundle\CoreBundle\Validator\UniqueEntityCollectionValidator
        arguments:
            - '@doctrine'
        tags:
            - { name: validator.constraint_validator, alias: unique_entity_collection }

    marello_core.twig.workflow_extension:
        class: Marello\Bundle\CoreBundle\Twig\WorkflowExtension
        arguments:
            - '@oro_workflow.manager'
        tags:
            - { name: twig.extension }