services:
    marello_core.workflow.action.workflow_transit_action:
        class: Marello\Bundle\CoreBundle\Workflow\Action\WorkflowTransitAction
        arguments:
            - '@oro_action.context_accessor'
            - '@oro_workflow.manager'
        tags:
            - { name: oro_workflow.action, alias: marello_core_transit_complete_action }