api:
    entities:
        Marello\Bundle\ProductBundle\Entity\Product:
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    sku:
                        data_type: string
                        allow_array: true
                        property_path: sku
                        description: 'Filter by sku'
                    createdAt:
                        exclude: true
                    updatedAt:
                        exclude: true