api:
    entities:
        Marello\Bundle\ProductBundle\Entity\Product:
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    sku:
                        data_type: string
                        allow_array: true
                        property_path: sku
                        description: 'Filter by sku'
                    name:
                        data_type: string
                        allow_array: true
                        property_path: name
                        description: 'Filter by name'
                    createdAt:
                        exclude: true
                    updatedAt:
                        exclude: true

#        Marello\Bundle\OrderBundle\Entity\Customer:
#            fields:
#                createdAt:
#                    exclude: true
#                updatedAt:
#                    exclude: true
#            filters:
#                exclusion_policy: all
#                fields:
#                    email:
#                        data_type: string
#                        allow_array: true
#                        property_path: email
#                        description: 'Filter by email'
#            actions:
#                delete: false
#                delete_list: false
#                delete_relationship: false