Marello\Bundle\CatalogBundle\Entity\Category:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: code
            message: 'marello.sales.messages.error.code'
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 255
        code:
            - NotBlank: ~
