parameters:

services:
    marello_return.form.type.return:
        class: Marello\Bundle\ReturnBundle\Form\Type\ReturnType
        arguments:
            - @marello_return.form.subscriber.return_type_subscriber
        tags:
            - { name: form.type, alias: marello_return }

    marello_return.form.type.return_item:
        class: Marello\Bundle\ReturnBundle\Form\Type\ReturnItemType
        tags:
            - { name: form.type, alias: marello_return_item }

    marello_return.form.type.return_item_collection:
        class: Marello\Bundle\ReturnBundle\Form\Type\ReturnItemCollectionType
        tags:
            - { name: form.type, alias: marello_return_item_collection }

    marello_return.form.subscriber.return_type_subscriber:
        class: Marello\Bundle\ReturnBundle\Form\Subscriber\ReturnTypeSubscriber
