parameters:

services:
    marello_return.form.type.return:
        class: Marello\Bundle\ReturnBundle\Form\Type\ReturnType
        arguments:
            - @marello_return.form.subscriber.return_type_subscriber
        tags:
            - { name: form.type, alias: marello_return }

    marello_return.form.type.return_api:
        class: Marello\Bundle\ReturnBundle\Form\Type\ReturnApiType
        tags:
            - { name: form.type, alias: marello_return_api }

    marello_return.form.type.return_item:
        class: Marello\Bundle\ReturnBundle\Form\Type\ReturnItemType
        tags:
            - { name: form.type, alias: marello_return_item }

    marello_return.form.type.return_item_collection:
        class: Marello\Bundle\ReturnBundle\Form\Type\ReturnItemCollectionType
        tags:
            - { name: form.type, alias: marello_return_item_collection }

    marello_return.form.subscriber.return_type_subscriber:
        class: Marello\Bundle\ReturnBundle\Form\Subscriber\ReturnTypeSubscriber

    marello_return.form.return_api:
            class: Symfony\Component\Form\Form
            factory_method: createNamed
            factory_service: form.factory
            arguments:
                - ~
                - 'marello_return_api'

    marello_return.form.handler.return_api:
        class: Marello\Bundle\ReturnBundle\Form\Handler\ReturnApiHandler
        scope: request
        arguments:
            - @marello_return.form.return_api
            - @request
            - @doctrine.orm.entity_manager
            - @oro_entity.routing_helper
