parameters:
    marello_return.entity.return.class: Marello\Bundle\ReturnBundle\Entity\ReturnEntity

services:
    marello_return.manager.return.api:
        class: Marello\Bundle\ReturnBundle\Entity\Manager\ReturnApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %marello_return.entity.return.class%
            - @doctrine.orm.entity_manager

    marello_return.util.return_helper:
        class: Marello\Bundle\ReturnBundle\Util\ReturnHelper
        arguments:
            - @doctrine.orm.entity_manager

    marello_return.twig.return_extension:
        class: Marello\Bundle\ReturnBundle\Twig\ReturnExtension
        arguments:
            - @marello_return.util.return_helper
        tags:
            - { name: twig.extension }

    marello_return.validator.ror_warranty:
        class: Marello\Bundle\ReturnBundle\Validator\ReturnRorWarrantyValidator
        arguments:
            - @oro_config.manager
        tags:
            - { name: validator.constraint_validator }