services:
    marello_return.listener.doctrine.return_number_generator_listener:
        class: Marello\Bundle\ReturnBundle\EventListener\Doctrine\ReturnNumberGeneratorListener
        tags:
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: postFlush }
