parameters:
    marello_return.entity.return.class: Marello\Bundle\ReturnBundle\Entity\ReturnEntity

services:
    marello_return.manager.return.api:
        class: Marello\Bundle\ReturnBundle\Entity\Manager\ReturnApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %marello_return.entity.return.class%
            - @doctrine.orm.entity_manager

    marello_return.util.return_helper:
        class: Marello\Bundle\ReturnBundle\Util\ReturnHelper

    marello_return.twig.return_extension:
        class: Marello\Bundle\ReturnBundle\Twig\ReturnExtension
        arguments:
            - @marello_return.util.return_helper
        tags:
            - { name: twig.extension }

    marello_return.email_processor_link:
        tags:
            - { name: oro_service_link, service: marello_notification.email.send_processor }

    marello_return.listener.return_created_notification_sender:
        class: Marello\Bundle\ReturnBundle\EventListener\ReturnCreatedNotificationSender
        arguments:
            - "@marello_return.email_processor_link"
        tags:
            - { name: kernel.event_listener, event: "marello.core.derived_property_set", method: derivedPropertySet }
