datagrid:
    marello_report-orders-revenue_per_sales_channel:
        pageTitle: marello.report.title.revenue_per_sales_channel
        source:
            type: orm
            acl_resource: oro_report_view
            query:
                select:
                    - channel.name as salesChannelName
                    - channel.currency
                    - COUNT(o.orderNumber) as totalOrders
                    - SUM(o.grandTotal) as totalRevenue
                from:
                    - { table: MarelloOrderBundle:Order, alias: o }
                join:
                    left:
                        - { join: o.salesChannel, alias: channel }
                groupBy: salesChannelName
        columns:
            salesChannelName:
                label: marello.order.sales_channel.label
                frontend_type: string
                data_name: salesChannelName
            totalOrders:
                label: marello.report.datagrid.columns.total_orders.label
                frontend_type: string
            totalRevenue:
                label: marello.report.datagrid.columns.total_revenue.label
                type:             localized_number
                method:           formatCurrency
                context_resolver: Marello\Bundle\DataGridBundle\Grid\FormatterContextResolver::getResolverCurrencyClosure
                align:            right
        sorters:
            columns:
                salesChannelName:       { data_name: salesChannelName }
                totalOrders:            { data_name: totalOrders }
                totalRevenue:           { data_name: totalRevenue }
            default:
                totalRevenue: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
        options:
            entityHint: report data
            export: false

    marello_report-products-low_stock_products:
        pageTitle: marello.report.title.low_stock_products
        source:
            type: orm
            acl_resource: oro_report_view
            query:
                select:
                    - p.name
                    - p.sku
                    - p.price
                    - s.label as status
                    - SUM(l.inventory) AS stockLevel
                from:
                    - { table: MarelloProductBundle:Product, alias: p }
                join:
                    left:
                        - { join: p.status, alias: s }
                        - { join: p.inventoryItems, alias: i }
                        - { join: i.currentLevel, alias: l }
                where:
                    and:
                        - l.inventory < 5
                groupBy: p.sku
        columns:
            sku:
                label:              marello.product.sku.label
                frontend_type:      string
            name:
                label:              marello.product.name.label
                frontend_type:      string
            stockLevel:
                label:              marello.product.stock_level.label
                frontend_type:      number
                data_name:          stockLevel
            status:
                label:              marello.product.status.label
                frontend_type:      string
            price:
                label:              marello.product.price.label
                frontend_type:      currency
        sorters:
            columns:
                sku:            { data_name: p.sku }
                name:           { data_name: p.name }
                stockLevel:     { data_name: stockLevel }
                status:         { data_name: s.label }
                price:          { data_name: p.price }
            default:
                stockLevel:  %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
        options:
            entityHint: report data
            export: false

    marello_report-orders-best_selling_items:
            pageTitle: marello.report.title.best_selling_items
            source:
                type: orm
                acl_resource: oro_report_view
                query:
                    select:
                        - oi.productName
                        - oi.productSku
                        - product.createdAt as createdAt
                        - SUM(oi.quantity) AS quantitySold
                    from:
                        - { table: MarelloOrderBundle:OrderItem, alias: oi }
                    join:
                        left:
                            - { join: oi.product, alias: product }
                    groupBy: oi.productSku, oi.productName
            columns:
                productSku:
                    label:              marello.product.sku.label
                    frontend_type:      string
                productName:
                    label:              marello.product.name.label
                    frontend_type:      string
                createdAt:
                    label:              oro.ui.created_at
                    frontend_type:      datetime
                quantitySold:
                    label:              marello.report.datagrid.columns.quantity_sold.label
                    frontend_type:      number
                    data_name:          quantitySold
            sorters:
                columns:
                    productSku:            { data_name: oi.productSku }
                    productName:           { data_name: oi.productName }
                    createdAt:             { data_name: createdAt }
                    quantitySold:          { data_name: quantitySold }
                default:
                    quantitySold:  %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
            options:
                entityHint: report data
                export: false
                toolbarOptions:
                    hide: true
                    pageSize:
                        items: [5]
                        default_per_page: 5

    marello_report-orders-worst_selling_items:
            pageTitle: marello.report.title.worst_selling_items
            source:
                type: orm
                acl_resource: oro_report_view
                query:
                    select:
                        - oi.productName
                        - oi.productSku
                        - product.createdAt as createdAt
                        - SUM(oi.quantity) AS quantitySold
                    from:
                        - { table: MarelloOrderBundle:OrderItem, alias: oi }
                    join:
                        left:
                            - { join: oi.product, alias: product }
                    groupBy: oi.productSku, oi.productName
            columns:
                productSku:
                    label:              marello.product.sku.label
                    frontend_type:      string
                productName:
                    label:              marello.product.name.label
                    frontend_type:      string
                createdAt:
                    label:              oro.ui.created_at
                    frontend_type:      datetime
                quantitySold:
                    label:              marello.report.datagrid.columns.quantity_sold.label
                    frontend_type:      number
                    data_name:          quantitySold
            sorters:
                columns:
                    productSku:            { data_name: oi.productSku }
                    productName:           { data_name: oi.productName }
                    createdAt:             { data_name: createdAt }
                    quantitySold:          { data_name: quantitySold }
                default:
                    quantitySold: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
            options:
                entityHint: report data
                export: false
                toolbarOptions:
                    hide: true
                    pageSize:
                        items: [5]
                        default_per_page: 5

    # All non aggregated columns are being added to the group by,
    # meaning that they will be added by default if no aggregated columns
    # are specifically grouped by
    #see https://github.com/orocrm/platform/issues/241#issuecomment-83146700
    marello_report-returns-returned_qty_by_reason:
            pageTitle: marello.report.title.returned_qty_by_reason
            source:
                type: orm
                acl_resource: oro_report_view
                query:
                    select:
                        - IDENTITY(ri.reason) as returnReason
                        - oi.productSku
                        - oi.productName
                        - SUM(ri.quantity) AS quantityReturned
                        - COUNT(o.id) as totalOrders
                    from:
                        - { table: MarelloReturnBundle:ReturnItem, alias: ri }
                    join:
                        left:
                            - { join: ri.orderItem, alias: oi }
                            - { join: ri.reason, alias: rre }
                            - { join: oi.order, alias: o }
                            - { join: o.workflowStep, alias: wfs }
                    where:
                        and:
                            - wfs.name = 'shipped'
            columns:
                productSku:
                    label:              marello.product.sku.label
                    frontend_type:      string
                productName:
                    label:              marello.product.name.label
                    frontend_type:      string
                returnReason:
                    context:
                        enum_code:      marello_return_reason
                        frontend_type:  enum
                    label:              marello.return.returnitem.reason.label
                totalOrders:
                    data_name:          totalOrders
                    label:              marello.report.datagrid.columns.total_orders.label
                    frontend_type:      number
                    align:              center
                quantityReturned:
                    data_name:          quantityReturned
                    label:              marello.report.datagrid.columns.quantity_returned.label
                    frontend_type:      number
                    align:              center
            sorters:
                columns:
                    productSku:             { data_name: oi.productSku }
                    productName:            { data_name: oi.productName }
                    quantityReturned:       { data_name: quantityReturned }
                    totalOrders:            { data_name: totalOrders }
                    returnReason:           { data_name: returnReason }
                default:
                    productSku: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
            filters:
                columns:
                    productSku:
                        type:           string
                        data_name:      oi.productSku
                    productName:
                        type:           string
                        data_name:      oi.productName
                    returnReason:
                        type: enum
                        enum_code: marello_return_reason
                        data_name: returnReason
            options:
                entityHint: report data
                export: false
