oro_menu_config:
    items:
        static_reports_tab:
            label: 'marello.report.menu.static_reports_tab.label'
            uri: '#'
            extras:
                position: 10

        orders_report_tab:
            label: 'marello.report.menu.orders_report_tab.label'
            uri: '#'
            extras:
                position: 5
                skipBreadcrumbs: true

        products_report_tab:
            label: 'marello.report.menu.products_report_tab.label'
            uri: '#'
            extras:
                position: 10
                skipBreadcrumbs: true

        returns_report_tab:
            label: 'marello.report.menu.returns_report_tab.label'
            uri: '#'
            extras:
                position: 5
                skipBreadcrumbs: true

        revenue_per_sales_channel:
            label: 'marello.report.menu.revenue_per_sales_channel.label'
            route: 'marello_report_index'
            routeParameters:
                reportGroupName: 'orders'
                reportName:      'revenue_per_sales_channel'
            extras:
                description: 'marello.report.menu.revenue_per_sales_channel.description'
                skipBreadcrumbs: true

        low_stock_products:
            label: 'marello.report.menu.low_stock_products.label'
            route: 'marello_report_index'
            routeParameters:
                reportGroupName: 'products'
                reportName:      'low_stock_products'
            extras:
                description: 'marello.report.menu.low_stock_products.description'
                skipBreadcrumbs: true

        best_selling_items:
            label: 'marello.report.menu.best_selling_items.label'
            route: 'marello_report_index'
            routeParameters:
                reportGroupName: 'orders'
                reportName:      'best_selling_items'
            extras:
                description: 'marello.report.menu.best_selling_items.description'
                skipBreadcrumbs: true

        worst_selling_items:
            label: 'marello.report.menu.worst_selling_items.label'
            route: 'marello_report_index'
            routeParameters:
                reportGroupName: 'orders'
                reportName:      'worst_selling_items'
            extras:
                description: 'marello.report.menu.worst_selling_items.description'
                skipBreadcrumbs: true

        returned_qty_by_reason:
            label: 'marello.report.menu.returned_qty_by_reason.label'
            route: 'marello_report_index'
            routeParameters:
                reportGroupName: 'returns'
                reportName:      'returned_qty_by_reason'
            extras:
                description: 'marello.report.menu.returned_qty_by_reason.description'
                skipBreadcrumbs: true

    tree:
        application_menu:
            children:
                reports_tab:
                    children:
                        static_reports_tab:
                            children:
                                orders_report_tab:
                                    children:
                                        revenue_per_sales_channel: ~
                                products_report_tab:
                                    children:
                                        low_stock_products: ~
                                        best_selling_items: ~
                                        worst_selling_items: ~
                                returns_report_tab:
                                    children:
                                        returned_qty_by_reason: ~

oro_titles:
    marello_report_index: '%%reportName%% - %%reportGroup%%'