datagrid:
    marello-products-grid:
        extended_entity_name: Marello\Bundle\ProductBundle\Entity\Product
        source:
            type: orm
            acl_resource: marello_product_view
            query:
                select:
                    - p.id
                    - p.name
                    - p.sku
                    - s.label as status
                    - p.stockLevel
                from:
                    - { table: Marello\Bundle\ProductBundle\Entity\Product, alias: p }
                join:
                    left:
                        - { join: p.status, alias: s }
        columns:
            sku:
                label:              marello.product.sku.label
                frontend_type:      string
            name:
                label:              marello.product.name.label
                frontend_type:      string
            stockLevel:
                label:              marello.product.stock_level.label
                frontend_type:      string
            status:
                label:              marello.product.status.label
                frontend_type:      string
        properties:
            id: ~
            view_link:
                type:       url
                route:      marello_product_view
                params:     [ id ]
            update_link:
                type:       url
                route:      marello_product_update
                params:     [ id ]
        sorters:
            columns:
                sku:            { data_name: p.sku }
                name:           { data_name: p.name }
                stockLevel:     { data_name: p.stockLevel }
                status:         { data_name: s.label }
            default:
                name:  DESC
        filters:
            columns:
                sku:
                    type:             string
                    data_name:        p.sku
                name:
                    type:             string
                    data_name:        p.name
                stockLevel:
                    type:             string
                    data_name:        p.stockLevel
                status:
                    type: entity
                    data_name: s
                    options:
                        field_options:
                            class: Marello\Bundle\ProductBundle\Entity\ProductStatus
        actions:
            view:
                type:           navigate
                label:          oro.grid.action.view
                link:           view_link
                icon:           eye-open
                acl_recource:   marello_product_view
                rowAction:      true
            update:
                type:           navigate
                acl_resource:   marello_product_update
                label:          marello.product.update
                icon:           edit
                link:           update_link
        options:
            entityHint: product
            export: true
            entity_pagination: true
