datagrid:
    marello-products-grid:
        extended_entity_name: Marello\Bundle\ProductBundle\Entity\Product
        source:
            type: orm
            acl_resource: marello_product_view
            query:
                select:
                    - p.id
                    - p.name
                    - p.sku
                    - p.price
                    - s.label as status
                    - p.stockLevel
                    - p.createdAt
                    - p.updatedAt
                from:
                    - { table: Marello\Bundle\ProductBundle\Entity\Product, alias: p }
                join:
                    left:
                        - { join: p.status, alias: s }
        columns:
            sku:
                label:              marello.product.sku.label
                frontend_type:      string
            name:
                label:              marello.product.name.label
                frontend_type:      string
            stockLevel:
                label:              marello.product.stock_level.label
                frontend_type:      string
            status:
                label:              marello.product.status.label
                frontend_type:      string
            price:
                label:              marello.product.price.label
                frontend_type:      string
            createdAt:
                label:              oro.ui.created_at
                frontend_type:      datetime
            updatedAt:
                label:              oro.ui.updated_at
                frontend_type:      datetime
        properties:
            id: ~
            view_link:
                type:       url
                route:      marello_product_view
                params:     [ id ]
            update_link:
                type:       url
                route:      marello_product_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      marello_product_api_delete_product
                params:     [ id ]
            inventory_link:
                type:       url
                route:      marello_inventory_inventory_update
                params:     [ id ]
        sorters:
            columns:
                sku:            { data_name: p.sku }
                name:           { data_name: p.name }
                stockLevel:     { data_name: p.stockLevel }
                status:         { data_name: s.label }
                price:          { data_name: p.price }
                createdAt:      { data_name: p.createdAt }
                updatedAt:      { data_name: p.updatedAt }
            default:
                name:  DESC
        filters:
            columns:
                sku:
                    type:             string
                    data_name:        p.sku
                name:
                    type:             string
                    data_name:        p.name
                stockLevel:
                    type:             string
                    data_name:        p.stockLevel
                status:
                    type: entity
                    data_name: s
                    options:
                        field_options:
                            class: Marello\Bundle\ProductBundle\Entity\ProductStatus
                price:
                    type:             string
                    data_name:        p.price
        actions:
            view:
                type:           navigate
                label:          oro.grid.action.view
                link:           view_link
                icon:           eye-open
                acl_recource:   marello_product_view
                rowAction:      true
            update:
                type:           navigate
                acl_resource:   marello_product_update
                label:          marello.product.update
                icon:           edit
                link:           update_link
            delete:
                type:           delete
                link:           delete_link
                acl_resource:   marello_product_delete
                icon:           trash
                label:          oro.grid.action.delete
            inventory:
                type:           navigate
                icon:           list-alt
                link:           inventory_link
        options:
            entityHint: product
            export: true
            entity_pagination: true

    marello-product-variant-grid:
        extended_entity_name: Marello\Bundle\ProductBundle\Entity\Product
        source:
            type: orm
            acl_resource: marello_product_view
            query:
                select:
                    - p.name
                    - p.sku
                    - p.price
                    - s.label as status
                    - p.stockLevel
                from:
                    - { table: Marello\Bundle\ProductBundle\Entity\Product, alias: p }
                join:
                    left:
                        - { join: p.status, alias: s }
                where:
                    and:
                        - p.variant = :variantId
                        - p.id != :productId
            bind_parameters:
                - variantId
                - productId
        columns:
            sku:
                label:              marello.product.sku.label
                frontend_type:      string
            name:
                label:              marello.product.name.label
                frontend_type:      string
            stockLevel:
                label:              marello.product.stock_level.label
                frontend_type:      string
            status:
                label:              marello.product.status.label
                frontend_type:      string
            price:
                label:              marello.product.price.label
                frontend_type:      string
        sorters:
            columns:
                name:           { data_name: p.name }
                sku:            { data_name: p.sku }
                price:          { data_name: p.price }
            default:
                stockLevel:  DESC
        options:
            entityHint: product
            toolbarOptions:
                hide: true
                pagination:
                    hide: true