Marello\Bundle\ProductBundle\Entity\Product:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: sku
            message: 'marello.product.messages.error.sku'
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 255
        sku:
            - NotBlank: ~
        price:
            - NotBlank: ~
            - Type:
                type: float
                message: The value {{ value }} is not a valid {{ type }}.