services:
    marello_productprice.pricing.provider.currency_provider:
        class: Marello\Bundle\PricingBundle\Provider\CurrencyProvider
        arguments:
            - '@doctrine'
            - '@oro_locale.settings'

    marello_productprice.pricing.provider.channelprice_provider:
        class: Marello\Bundle\PricingBundle\Provider\ChannelPriceProvider
        arguments:
            - '@doctrine'
        tags:
            - { name: marello_order.order_item_data_provider, type: price, priority: 10 }

    marello_productprice.pricing.form.event_listener.pricing_subscriber:
        class: Marello\Bundle\PricingBundle\Form\EventListener\PricingSubscriber
        arguments:
            - '@marello_productprice.pricing.provider.currency_provider'

    marello_productprice.pricing.form.event_listener.channel_pricing_subscriber:
        class: Marello\Bundle\PricingBundle\Form\EventListener\ChannelPricingSubscriber
        arguments:
            - '@doctrine.orm.entity_manager'
            - Marello\Bundle\PricingBundle\Model\PricingAwareInterface
            - '@marello_sales.saleschannel.provider.channel_provider'

    marello_productprice.pricing.twig.pricing_extension:
        class: Marello\Bundle\PricingBundle\Twig\PricingExtension
        arguments:
            - '@marello_productprice.pricing.provider.currency_provider'
        tags:
            - { name: twig.extension }

    marello_productprice.pricing.subtotal_provider.composite:
        class: Marello\Bundle\PricingBundle\Subtotal\Provider\CompositeSubtotalProvider
        arguments:
            - '@translator'
            - '@oro_currency.rounding.price_rounding_service'
            - '@oro_currency.config.currency'

    marello_productprice.pricing.subtotal_provider.subtotal_line_item:
        class: Marello\Bundle\PricingBundle\Subtotal\Provider\LineItemSubtotalProvider
        arguments:
            - '@translator'
            - '@oro_currency.rounding.price_rounding_service'
            - '@oro_currency.config.currency'
        calls:
            - ['addDependOnProvider', ['@marello_tax.provider.tax_subtotal', 2]]
        tags:
            - { name: marello_pricing.subtotal_provider, priority: 20 }