Marello\Bundle\PricingBundle\Entity\ProductPrice:
    properties:
        product:
            - NotBlank: ~
        currency:
            - NotBlank: ~
        type:
            - NotBlank: ~

Marello\Bundle\PricingBundle\Entity\ProductChannelPrice:
    constraints:
        - Marello\Bundle\CoreBundle\Validator\Constraints\UniqueEntityCollection:
            fields: [channel, currency, type]
            errorPath: channel
            message: 'marello.pricing.productchannelprice.messages.error.unique_channel_price'
    properties:
        product:
            - NotBlank: ~
        channel:
            - NotBlank: ~
        currency:
            - NotBlank: ~
        type:
            - NotBlank: ~