Marello\Bundle\PricingBundle\Entity\ProductChannelPrice:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [channel, currency]
            message: 'marello.pricing.productchannelprice.messages.error.unique_channel_price'
    properties:
        channel:
            - NotBlank: ~
        currency:
            - NotBlank: ~
        value:
            - NotBlank: ~
