services:
    ## load_data
    marello_extendworkflow.load_workflowitems_for_entity:
        class: Marello\Bundle\ExtendWorkflowBundle\Api\Processor\Get\LoadWorkflowItemsForEntity
        arguments:
            - '@oro_workflow.manager'
            - '@oro_workflow.repository.workflow_item'
        tags:
            - { name: oro.api.processor, action: get, group: load_data, requestType: json_api, priority: 100 }

#    marello_extendworkflow.load_workflowitems_for_entities:
#        class: Marello\Bundle\ExtendWorkflowBundle\Api\Processor\GetList\LoadWorkflowItemsForEntities
#        tags:
#            - { name: oro.api.processor, action: get_list, group: load_data, requestType: json_api, priority: 100 }