services:
    marello_extendedworkflow.extension.start_transition_button_provider:
        class: 'Marello\Bundle\ExtendWorkflowBundle\Extension\StartTransitionButtonProviderExtension'
        arguments:
            - '@oro_workflow.registry'
            - '@oro_workflow.provider.start_transition_route'
        tags:
           - { name: oro.action.extension.button_provider, priority: 110 }

    marello_extendedworkflow.extension.transition_button_provider:
        class: 'Marello\Bundle\ExtendWorkflowBundle\Extension\TransitionButtonProviderExtension'
        arguments:
            - '@oro_workflow.registry'
            - '@oro_workflow.provider.transition_route'
        tags:
           - { name: oro.action.extension.button_provider, priority: 120 }